name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.17.1
  firebase_auth: 3.3.19
  cloud_firestore: 3.1.17
  font_awesome_flutter: ^10.3.0
  google_sign_in: ^5.4.4
  convex_bottom_bar: 3.2.0
  intl: ^0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/lottiefiles/
  uses-material-design: true

