name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 1.17.1
  firebase_auth: 3.3.19
  cloud_firestore: 3.1.17
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  google_sign_in: ^5.4.3
  camera: ^0.10.2+1
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1
  google_ml_kit: ^0.7.3
  path_provider: ^2.0.9
  
dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - mobilefacenet.tflite
    - assets/lottiefiles/
    - assets/icons/
  uses-material-design: true


