// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOjgH6_zR_Zo1JDO_RVM3YgZlwivaNEf4',
    appId: '1:678243313377:web:6769f8ff6034898b8eb9a0',
    messagingSenderId: '678243313377',
    projectId: 'presence-4b820',
    authDomain: 'presence-4b820.firebaseapp.com',
    storageBucket: 'presence-4b820.appspot.com',
    measurementId: 'G-0NK5Z6Z239',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO9d_vJ7onXMc81A_ivYXYRITEsnZvKDA',
    appId: '1:678243313377:android:c2698a4a1be56d558eb9a0',
    messagingSenderId: '678243313377',
    projectId: 'presence-4b820',
    storageBucket: 'presence-4b820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZOxiSFpEJUbSfGtnVWcOAubkCw3PbI7g',
    appId: '1:678243313377:ios:537a0993626aa31b8eb9a0',
    messagingSenderId: '678243313377',
    projectId: 'presence-4b820',
    storageBucket: 'presence-4b820.appspot.com',
    iosClientId: '678243313377-v8oroedg8c9dmg540d0obe92qjld17db.apps.googleusercontent.com',
    iosBundleId: 'com.man.presence',
  );
}
